# Generated by Django 4.1.3 on 2022-12-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('npp', models.PositiveSmallIntegerField(default=0, verbose_name='сортировка')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'db_table': 'quiz',
                'ordering': ('npp',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, verbose_name='вопрос')),
                ('full_text', models.TextField(blank=True, verbose_name='описание вопроса')),
                ('image', models.ImageField(blank=True, upload_to='quiz/%Y/', verbose_name='изображение')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opros.quiz', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150, verbose_name='ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='правильный ответ')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='комментарий к ответу')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opros.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
                'db_table': 'answers',
            },
        ),
    ]
