# Generated by Django 4.1.3 on 2022-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('user_number', models.IntegerField(blank=True, verbose_name='Табельный номер')),
            ],
        ),
    ]
