# Generated by Django 4.1.3 on 2022-12-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opros', '0004_question_user_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_input',
        ),
    ]
