# Generated by Django 4.1.3 on 2022-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opros', '0007_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='random_list',
            field=models.CharField(blank=True, max_length=250, verbose_name='random list'),
        ),
    ]
