# Generated by Django 4.1.3 on 2022-12-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opros', '0008_userinput_random_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='user_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Табельный номер'),
        ),
    ]
